<?php
echo $this->partial('layout/component/modules_nav_header');

?>
<div class="card">
    <div class="card-body">
        <div>
            <form action="<?=$curr_url;?>/save" method="post" enctype="multipart/form-data" id="editForm" class="row g-3">
                <input type="hidden" name="id" value="<?=$data['id'] ?? ''; ?>">
                <div class="col-md-9">
                    <?=$this->partial("layout/box/lang_name");?>
                </div>
                <div class="col-md-3">
                    <div class="row">
                        <div class="col-12">
                            <?=$this->partial("layout/box/path_lists");?>
                        </div>
                        <div class="col-12">
                            <?=$this->partial("layout/component/pictureBox");?>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
