<?php
// cil-ban
// cil-circle
// cil-happy
// cil-comment-bubble

$icons = [
    'active' => 'cil-sun',
    'hiden' => 'cil-moon',
    'delete' => 'cil-trash',
    'unbanned' => 'cil-circle',
    'banned' => 'cil-ban',
    'closed' => 'cil-mouth-slash',
    'delivered' => 'cil-car-alt'
];

?>
<header class="header header-sticky mb-4" style="top: 120px;">
    <div class="container-fluid">
        <?php
        if(!empty($current_module))
        {
            if(in_array($current_module, ['lots','users']))
            {
                echo $this->partial('layout/stats/'.$current_module);
            }
        }
        ?>

        <div class="row w-100">
            <div class="col-md-12">
                <div class="d-flex justify-content-between">
                    <div id="manipulateBtn">

                        <?php
                        $getBtn = function($val, $title) use ($icons) {
                            $icon = !empty($icons[$val]) ? $icons[$val] : 'cil-settings';
                            $result = '<button class="me-2 btn btn-primary" id="'.$val.'Btn" type="button" disabled>
                                            <svg class="icon me-2">
                                                <use xlink:href="/assets/icons/sprites/free.svg#'.$icon.'"></use>
                                            </svg>'.$title.'
                                        </button>';
                            return $result;
                        };

                        if(!empty($current_action) && $current_action=='index' && !empty($modules[$current_module]['control']))
                        {
                            echo '<input class="form-check-input mt-2 mx-2 me-4" id="checkAllItems" type="checkbox">';
                            foreach (new \ArrayIterator($modules[$current_module]['control']) as $key => $title)
                            {
                                if(!\in_array($key, ['index','save','roles']))
                                {
                                    echo $getBtn($key, $title);
                                }
                            }
                        }
                        ?>
                    </div>

                    <?php
                    if(!empty($current_action) && $current_action=='index')
                    {
                        echo $this->partial('layout/box/searchForm');
                    }

                    ?>

                    <div>
                        <?php
                        echo $this->partial('layout/component/rolesInit');
                        if(!empty($modules[$current_module]['control']['save']))
                        {
                            if($current_action=='index')
                            {
                                echo '<a href="'.$curr_url.'/save" class="btn btn-danger text-white">Добавить</a> ';
                            } else {
                                echo ' <button form="editForm" class="btn btn-danger text-white" type="submit">Сохранить</button> ';
                                echo ' <a href="'.$curr_url.'" class="btn btn-light">Отмена</a>';
                            }
                        }

                        if(!empty($current_module))
                        {
                            if($current_module=='lots')
                            {
                                echo $this->partial('layout/sorts/lots');
                            }
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>



