
<script src="/assets/js/__/__/build/ckeditor.js"></script>
<script>
    let EditorConfigs = {
        toolbar: {
            items: [
                'code',
                '|',
                'undo',
                'redo',
                '|',
                'heading',
                '|',
                'alignment',
                'bold',
                'italic',
                'underline',
                'link',
                'bulletedList',
                'numberedList',
                '|',
                'fontColor',
                'fontSize',
                'fontFamily',
                '|',
                'imageInsert',
                'blockQuote',
                'insertTable',
                'mediaEmbed',
                'htmlEmbed',
                '|',
                'removeFormat'
            ]
        },
        language: 'ru',
        table: {
            contentToolbar: [
                'tableColumn',
                'tableRow',
                'mergeTableCells',
                'tableCellProperties',
                'tableProperties'
            ]
        },
        fontSize: {
            options: [
                9,
                11,
                13,
                'default',
                17,
                19,
                21
            ]
        },
        image: {
            styles: [
                'alignLeft', 'alignCenter', 'alignRight'
            ],
            resizeOptions: [
                {
                    name: 'imageResize:original',
                    label: 'Исходный',
                    value: null
                },
                {
                    name: 'imageResize:75',
                    label: '75%',
                    value: '75'
                },
                {
                    name: 'imageResize:50',
                    label: '50%',
                    value: '50'
                },
                {
                    name: 'imageResize:35',
                    label: '35%',
                    value: '35'
                },
                {
                    name: 'imageResize:25',
                    label: '25%',
                    value: '25'
                },
                {
                    name: 'imageResize:15',
                    label: '15%',
                    value: '15'
                }
            ],
            toolbar: [
                'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:alignRight',
                '|',
                'imageResize',
                '|',
                'imageTextAlternative'
            ]
        }
    };
    let editors = [];
    function createEditor(elementId) {
        return ClassicEditor
            .create( document.querySelector(elementId), EditorConfigs)
            .then( editor => {
                editors[ elementId ] = editor;
                editor.setData(document.querySelector(elementId).value);
            } )
            .catch( err => console.error( err ) );
    }
</script>