<div class="dropdown-menu dropdown-menu-end dropdown-menu-lg pt-0">
    <div class="dropdown-header bg-light dark:bg-white dark:bg-opacity-10">
        <strong>Сообщения</strong></div>
        <a class="dropdown-item" href="#">
            <div class="message">
                <!--<div class="py-3 me-3 float-start">
                    <div class="avatar"><img class="avatar-img" src="assets/img/avatars/7.jpg" alt="user@email.com"><span class="avatar-status bg-success"></span></div>
                </div>
                <div><small class="text-medium-emphasis">John Doe</small><small class="text-medium-emphasis float-end mt-1">Just now</small></div>
                <div class="text-truncate font-weight-bold"><span class="text-danger">!</span> Important message</div>
                <div class="small text-medium-emphasis text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</div>-->
            </div>
        </a>
        <a class="dropdown-item text-center border-top" href="#">
            <strong>Перейти ко всем сообщениям</strong>
        </a>
</div>