<div class="dropdown-menu dropdown-menu-end dropdown-menu-lg pt-0">
    <div class="dropdown-header bg-light dark:bg-white dark:bg-opacity-10">
        <strong>Уведомления</strong>
    </div>
    <a class="dropdown-item" href="#">
        <svg class="icon me-2 text-success">
            <use xlink:href="/assets/icons/sprites/free.svg#cil-user-follow"></use>
        </svg> Новые пользователи</a>
    <a class="dropdown-item" href="#">
        <svg class="icon me-2 text-info">
            <use xlink:href="/assets/icons/sprites/free.svg#cil-chart"></use>
        </svg> Новые лоты</a>
    <a class="dropdown-item" href="#">
        <svg class="icon me-2 text-success">
            <use xlink:href="/assets/icons/sprites/free.svg#cil-basket"></use>
        </svg> Продажи</a>
</div>