<?php
use Phalcon\Config;
return new Config([
    'advertising' => ['view','save','active','hiden','delete'],
    'pages' => ['view','save','active','hiden','delete'],
    'news' => ['view','save','active','hiden','delete'],
    'languages' => ['view','save','delete'],
    'category' => ['view','save','delete'],
    'heroes' => ['view','save','delete'],
    'producer' => ['view','save','delete'],
    'entity_type' => ['view','save','delete'],
    'brands' => ['view','save','delete'],
    'brands_universe' => ['view','save','delete'],
    'currency' => ['view','save','delete'],
    'currency_course' => ['view','save','delete'],
    'products' => ['view','save','delete'],
    'interests' => ['view','save','delete'],
    'paid_services' => ['view','save','delete'],
    'shops' => ['view','banned','unbanned','delete'],
    'album' => ['view','banned','unbanned','delete'],
    'offers' => ['view','moderated','banned','unbanned','delete'],
    'blogs' => ['view','banned','unbanned','delete'],
    'reviews' => ['view','banned','unbanned','delete'],
    'community' => ['view','banned','unbanned','delete'],
    'orders' => ['view','delete'],
    'payments' => ['view','save','delete'],
    'notifications' => ['view','save','delete'],
    'roles' => ['view','save','delete'],
    'status' => ['view','save','delete'],
    'guest' => ['view','banned','unbanned','delete'],
    'users' => ['view','moderated','banned','unbanned','delete'],
]);
