<?php
echo $this->partial('layout/component/itemDropdown');
echo $this->partial('layout/component/modules_nav_header');
?>
<div class="card">
    <div class="card-body">
        <form action="<?=$curr_url;?>/save" method="post" id="editForm" class="row g-3">
            <input type="hidden" name="id" value="<?=$data['id'] ?? ''; ?>">
            <div class="col-md-7">
                <label class="form-label"><?=$local->_('name');?></label>
                <input class="form-control" name="name" type="text" value="<?=$data['name'] ?? '';?>" required>
            </div>
            <div class="col-md-5">
                <label class="form-label">Path key</label>
                <input class="form-control" name="path" type="text" value="<?=$data['path'] ?? '';?>" required>
            </div>
            <div class="col-md-12">
                <div class="row">
                    <?php
                    if(!empty($modules))
                    {
                        $initModules = (!empty($data['modules']) && !is_null($data['modules']))
                            ? json_decode($data['modules'], true)
                            : [];
                        foreach ((new ArrayIterator($modules)) as $key_modules => $module)
                        {
                            echo '<div class="col-6 g-3">';
                            echo '  <div class="card">';
                            echo '      <div class="card-header">'. $local->_('module_title') .' <strong>«'.$local->_($key_modules).'»</strong></div>';
                            echo '      <div class="card-body">';
                            echo '          <div class="row">';
                            foreach ($module as $control)
                            {
                                $checkedinit = '';
                                if(!empty($initModules[$control]) && in_array($control, $initModules[$control]))
                                {
                                    $checkedinit = 'checked';
                                }
                                echo '              <div class="col-12">';
                                echo '                  <div class="form-check form-switch form-switch-xl">';
                                echo '                      <input name="modules['.$key_modules.'][]" value="'.$control.'" class="form-check-input models-control" id="'.$key_modules.$control.'" type="checkbox" '.$checkedinit.'>';
                                echo '                      <label class="form-check-label" for="'.$key_modules.$control.'">'.$local->_($control).'</label>';
                                echo '                  </div>';
                                echo '              </div>';
                            }
                            echo '          </div>';
                            echo '      </div>';
                            echo '  </div>';
                            echo '</div>';
                        }
                    }
                    ?>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    const superadminId = document.querySelector('#superadminId');
    const controls = document.querySelectorAll('.models-control');
    superadminId.addEventListener('change', el => {
        if(el.target.checked)
        {
            controls.forEach(control => {
                control.checked = el.target.checked;
            });
        }
    });
</script>