<?php
//echo $this->partial('layout/component/itemDropdown');
echo $this->partial('layout/component/modules_nav_header');

$default = '';
if(!empty($data['defaults']) && $data['defaults']===true)
{
    $default = 'checked';
}
?>
<div class="card">
    <div class="card-body">
        <div>
            <form action="<?=$curr_url;?>/save" method="post" id="editForm" class="row g-3">
                <input type="hidden" name="id" value="<?=$data['id'] ?? ''; ?>">
                <div class="col-md-6">
                    <label class="form-label"><?=$local->_('label_name');?></label>
                    <input class="form-control" name="name" type="text" minlength="2" value="<?=$data['name'] ?? '';?>" required>
                </div>
                <div class="col-md-3">
                    <label class="form-label"><?=$local->_('label_code');?></label>
                    <input class="form-control" name="code" type="text" minlength="2" maxlength="2" value="<?=$data['code'] ?? '';?>" required>
                </div>
                <div class="col-md-3">
                    <label class="form-label"><?=$local->_('label_lang_title');?></label>
                    <div class="form-check form-switch form-switch-xl">
                        <label class="form-check-label" for="default_check"><?=$local->_('label_default');?></label>
                        <input type="checkbox" name="defaults" value="1" class="form-check-input models-control" id="default_check" <?=$default;?> />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
