<?php
echo $this->partial('layout/component/itemDropdown');
echo $this->partial('layout/component/modules_nav_header');
?>
<div class="card">
    <div class="card-body">
        <div>
            <?php
            if(!empty($data->total_count) && $data->total_count > 0)
            {
                echo '<table class="table table-hover mb-0 w-100">';
                echo '  <tbody>';
                foreach ($data->items as $item)
                {
                    echo '<tr class="align-middle">';
                    echo '  <td><input type="checkbox" class="form-check-input mt-2 itemCheck" name="items[]" value="'.$item['id'].'" /></td>';
                    echo '  <td>'.$item['code'].'</td>';
                    echo '  <td class="w-100">';
                    echo '      <div class="d-flex justify-content-between">';
                    echo '        <div>'.$item['name'].'</div>';
                    if($item['defaults']===true)
                    {
                        echo '    <div class="px-2 text-">' . $local->_('label_default') . '</div>';
                    }
                    echo '      </div>';
                    echo '  </td>';
                    echo '  <td>'.$initDropdown($item['id']).'</td>';
                    echo '</tr>';
                }
                echo '  </tbody>';
                echo '</table>';
            }
            ?>
        </div>
    </div>
</div>
