<?php
echo $this->partial('layout/component/modules_nav_header');
$data_content = [];
if(!empty($data['content']))
{
    $data_content = json_decode($data['content'], true);
}
?>
<div class="card">
    <div class="card-body">
        <div>
            <form action="<?=$curr_url;?>/save" method="post" enctype="multipart/form-data" id="editForm" class="row g-3">
                <input type="hidden" name="id" value="<?=$data['id'] ?? ''; ?>">
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-6">
                            <label class="form-label"><?=$local->_('label_name');?></label>
                            <input class="form-control" name="name" value="<?=$data['name'] ?? '';?>" />
                        </div>
                        <div class="col-6 ">
                            <label class="form-label"><?=$local->_('label_menu');?></label>
                            <div class="btn-group d-flex" role="group" aria-label="Basic radio toggle button group">
                                <?php
                                $menu_items = new \ArrayIterator(['top','left','right','bottom','footer']);
                                $checkedMenu = $data['menu'] ?? 'top';
                                foreach ($menu_items as $menu_key)
                                {
                                    $checked = $checkedMenu==$menu_key ? 'checked' : '';
                                    echo '<input class="btn-check" id="menu'.$menu_key.'" type="radio" name="menu" value="'.$menu_key.'" autocomplete="off" '.$checked.'>';
                                    echo '<label class="btn btn-outline-primary" for="menu'.$menu_key.'">'.$local->_('menu_'.$menu_key).'</label>';
                                }
                                ?>
                            </div>
                        </div>
                        <div class="col-12 mt-3">
                            <?php
                            if(!empty($langs))
                            {
                                $active_tab = 'active';
                                echo '<ul class="nav nav-tabs" id="contentTab" role="tablist">';
                                foreach (new \ArrayIterator($langs) as $lang)
                                {
                                    $tab_id = 'lang-'.$lang['code'];
                                    echo '<li class="nav-item" role="presentation">';
                                    echo '  <button class="nav-link '.$active_tab.'" id="'.$tab_id.'-tab" data-coreui-toggle="tab" data-coreui-target="#'.$tab_id.'" type="button" role="tab" aria-controls="'.$tab_id.'" aria-selected="true">'.$lang['name'].'</button>';
                                    echo '</li>';
                                    $active_tab = '';
                                }
                                echo '</ul>';
                                $active_tab = 'show active';
                                echo '<div class="tab-content" id="newsTabContent">';
                                foreach (new \ArrayIterator($langs) as $lang)
                                {
                                    $tab_id = 'lang-'.$lang['code'];
                                    $set_name = $data_content[$lang['code']]['name'] ?? '';
                                    $set_title = $data_content[$lang['code']]['title'] ?? '';
                                    $set_keywords = $data_content[$lang['code']]['keywords'] ?? '';
                                    $set_description = $data_content[$lang['code']]['description'] ?? '';
                                    $set_content = $data_content[$lang['code']]['content'] ?? '';
                                    $data_item = 'newsLang-'.$lang['code'];
                                    echo '<div class="tab-pane fade '.$active_tab.'" id="'.$tab_id.'" role="tabpanel" aria-labelledby="'.$tab_id.'tab">';
                                    echo '  <div class="mb-3 mt-3">';
                                    echo '      <label for="'.$data_item.'-name" class="form-label">'.$local->_('lang_content_name', ['lang'=>$lang['name']]).'</label>';
                                    echo '      <input type="text" name="content['.$lang['code'].'][name]" class="form-control" min="10" maxlength="255" id="'.$data_item.'-name" value="'.$set_name.'" />';
                                    echo '  </div>';
                                    echo '  <div class="mb-3">';
                                    echo '      <label class="form-label">'.$local->_('lang_content_title', ['lang'=>$lang['name']]).'</label>';
                                    echo '      <textarea class="form-control noresize" name="content['.$lang['code'].'][title]">'.$set_title.'</textarea>';
                                    echo '  </div>';
                                    echo '  <div class="mb-3">';
                                    echo '      <label class="form-label">'.$local->_('lang_content_keywords', ['lang'=>$lang['name']]).'</label>';
                                    echo '      <textarea class="form-control noresize" name="content['.$lang['code'].'][keywords]">'.$set_keywords.'</textarea>';
                                    echo '  </div>';
                                    echo '  <div class="mb-3">';
                                    echo '      <label class="form-label">'.$local->_('lang_content_description', ['lang'=>$lang['name']]).'</label>';
                                    echo '      <textarea class="form-control noresize" name="content['.$lang['code'].'][description]">'.$set_description.'</textarea>';
                                    echo '  </div>';
                                    echo '  <div class="mb-3">';
                                    echo '      <label for="'.$data_item.'-content" class="form-label">'.$local->_('lang_content_content', ['lang'=>$lang['name']]).'</label>';
                                    echo '      <textarea class="form-control" name="content['.$lang['code'].'][content]" id="'.$data_item.'-content" rows="3">'.$set_content.'</textarea>';
                                    echo '  </div>';
                                    echo '</div>';
                                    $active_tab = '';
                                }
                                echo '</div>';
                            }
                            ?>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="row">
                        <div class="col-12">
                            <?=$this->partial("layout/box/active_check");?>
                        </div>
                        <div class="col-12 mb-4 mt-2">
                            <?php
                            if(!empty($lists))
                            {
                                if(!empty($data['id']) && is_null($data['parent']))
                                {
                                    echo '<label class="form-label h3">'.$local->_('label_parent_is').'</label>';
                                } else {
                                    echo '<label class="form-label">'.$local->_('label_parent').'</label>';
                                    echo '<select class="form-select" name="parent" required>';
                                    foreach (new \ArrayIterator($lists) as $item)
                                    {
                                        $selected = '';
                                        $disabled = '';
                                        if(!empty($data['parent']) && !is_null($data['parent']))
                                        {
                                            if($item['id']==$data['parent'])
                                            {
                                                $selected = ' selected ';
                                            }
                                            if($item['id']==$data['id'])
                                            {
                                                $disabled = ' disabled ';
                                            }
                                        }
                                        $level = ($item['level'] > 1) ? str_repeat('&nbsp;&nbsp;', $item['level']) : '';
                                        echo '<option value="'.$item['id'].'" '.$selected.$disabled.'>'.$level.$item['name'].'</option>';
                                    }
                                    echo '</select>';
                                }

                            }
                            ?>
                        </div>
                        <div class="col-12">
                            <?=$this->partial("layout/box/pagesModules");?>
                        </div>
                        <div class="col-12">
                            <?=$this->partial("layout/component/pictureBox");?>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<?=$this->partial("layout/component/wysiwygBlocks");?>
<script>
    <?php
    if(!empty($langs))
    {
        foreach (new \ArrayIterator($langs) as $lang)
        {
            echo "createEditor('#newsLang-".$lang['code']."-content');";
        }
    }
    ?>
</script>
